# Generated by Django 4.2.3 on 2023-07-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Biography', 'Biography'), ('Adventure', 'Adventure'), ('Novels/Comics', 'Novels/Comics')], max_length=20),
        ),
    ]
