# Generated by Django 4.2.3 on 2023-07-23 10:11

import Books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to=Books.models.nameFile, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='books',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=Books.models.nameFile, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])]),
        ),
    ]
