# Generated by Django 4.2.3 on 2023-07-23 10:29

import Books.models
import Books.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_alter_books_book_file_alter_books_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to=Books.models.nameFile, validators=[Books.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
